name: new-nest-ci
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Checkov Scan Dockerfile
        run: |
          output=`docker run --tty --volume ${{ github.workspace }}:/wd bridgecrew/checkov --file /wd/Dockerfile --compact --quiet --soft-fail --skip-check CKV_DOCKER_2`
          echo $output
          result=`echo $output | sed 's/, /\n/g' | grep 'Failed checks' | awk -F ': ' '{print $1+$2}'`
          echo "Exit ${result}"
          exit $result
        shell: bash

