name: new-nest-ci
on: push

env:
  tag: $(NBGV_SemVer1)
  projectName: "new-nest"
  repository: "new-nest"
  acr: "devoperation.azurecr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NBGV
        uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          setAllVars: true

      - name: Set Version
        run: echo 'tag=${{ steps.nbgv.outputs.SemVer1 }}' >> $GITHUB_ENV
        if: ${{ github.ref_name == 'main' }}
      
      - name: Set Tag to BuildNumber
        run: echo "tag=${{ github.run_number }}" >> $GITHUB_ENV
        if: ${{ github.ref_name != 'main' }}

      - name: Checkov Scan Dockerfile
        run: |
          output=`docker run --tty --volume ${{ github.workspace }}:/wd bridgecrew/checkov --file /wd/Dockerfile --compact --quiet --soft-fail --skip-check CKV_DOCKER_2`
          echo $output
          result=`echo $output | sed 's/, /\n/g' | grep 'Failed checks' | awk -F ': ' '{print $1+$2}'`
          echo "Exit ${result}"
          exit $result
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.acr }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.acr }}/${{ env.repository }}:${{ env.tag }}
