name: new-nest-ci
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkov Scan Dockerfile
        run: |
          echo "working directory: ${GITHUB_WORKSPACE}"
          output=`docker run --tty --volume $(GITHUB_WORKSPACE):/wd bridgecrew/checkov --file /wd/Dockerfile --compact --quiet`
          echo $output
          result=`echo $output | sed 's/, /\n/g' | grep 'Failed checks' | awk -F ': ' '{print $1+$2}'`
          if [ -z "$result" ] ; then result=1 ; else result=0 ; fi
          echo "Exit ${result}"
          exit $result
