name: new-nest-ci
on: push

env:
  tag: ${NBGV_SEMVER1}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NBGV
        uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          setAllVars: true
          
      # - name: Install dotnet
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: '6.0.x'

      # - name: Install NBGV
      #   run: dotnet tool install --tool-path . nbgv

      - name: Set Version
        run: echo 'tag=${{ steps.nbgv.outputs.SemVer1 }}' >> $GITHUB_ENV
        if: ${{ github.ref_name == 'main' }}
      
      - name: Set Tag to BuildNumber
        run: echo "tag=${{ github.run_number }}" >> $GITHUB_ENV
        if: ${{ github.ref_name != 'main' }}

      - name: Echo env
        run: env.tag


      - name: Checkov Scan Dockerfile
        run: |
          output=`docker run --tty --volume ${{ github.workspace }}:/wd bridgecrew/checkov --file /wd/Dockerfile --compact --quiet --soft-fail --skip-check CKV_DOCKER_2`
          echo $output
          result=`echo $output | sed 's/, /\n/g' | grep 'Failed checks' | awk -F ': ' '{print $1+$2}'`
          echo "Exit ${result}"
          exit $result
        shell: bash

