name: new-nest-ci
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkov Scan Dockerfile
        run: |
          output=`docker run --tty --volume $(GITHUB_WORKSPACE):/wd bridgecrew/checkov --file /wd/Dockerfile --compact --quiet`
          echo $output
          result=`echo $output | sed 's/, /\n/g' | grep 'Failed checks' | awk -F ': ' '{print $1+$2}'`
          echo "Exit ${result}"
          exit $result
